# Generated by Django 5.1.4 on 2025-01-16 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chain", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chain",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chain_contact",
                to="chain.contact",
                verbose_name="Контакты",
            ),
        ),
        migrations.AlterField(
            model_name="chain",
            name="product",
            field=models.ManyToManyField(
                related_name="chain_product",
                to="chain.product",
                verbose_name="Продукты",
            ),
        ),
    ]
